### ISSUE TITLE
maybe try to implement under linux

### ISSUE THREAD

**Issue by qcq** [VedantParanjape/Chat-Server-and-Client#2]
just want to found what you used, in first thought I think that may be boost(asio) or plus websocket. seems it is not.

**Comment by Ankitkj1999** [comment]
Hi Vadant, i tried implementing your chat server-client project. But I am not able to get through with this, I am using dev c++ and whenever I hit compile it marks header file saying not present. 
Will you please guide me through. 

And I didn't find any other way to contact you so this!

**Comment by VedantParanjape** [comment]
> just want to found what you used, in first thought I think that may be boost(asio) or plus websocket. seems it is not.

I am seeing this now, this was my school project for learning, and it is unmaintained.

**Comment by VedantParanjape** [comment]
> just want to found what you used, in first thought I think that may be boost(asio) or plus websocket. seems it is not.

I used the windows socket library
